config/routes.rb
Rails.application.routes.draw do
  get '/questions', to: 'questions#index'
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @name = params[:name]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index 
    @questions = Question.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path%></li>
        <li><%= link_to 'Questions', questions_path%></li>
      </ul>
    </nav>
  <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcom to blog</h1>
&copy; @kelzerock <%=Time.now.year%>

app/views/questions/index.html.erb
<h1>questions</h1>


<%@questions.each do |item|%>
<h2><%=item.title%></h2>
<time datetime="<%=item.formatted_created_at%>">
<%= item.formatted_created_at%> 
</time>
<p>
  <%=item.body%>
</p>
<%end%>